# Project name
TARGET = dreamdash

# Project version
VERSION = 0.81

# Autoboot applications if found
AUTOBOOT = 0

# Wallpaper name
# - `lite-wall-128`
# - `lite-wall-256`
# - `lite-wall-512`
# - `dark-wall-128`
# - `dark-wall-256`
# - `dark-wall-512`
WALLPAPER_NAME = lite-wall-128

# Include support for launching discs
DISC_SUPPORT = 1

# Choose a FAT filesystem library:
# - `kosfat` for libkosfat (built into KOS)
# - `fatfs` for FatFS (addon library)
FAT_LIBRARY = fatfs

# Use Dreamcast's BIOS font instead of bitmap font
ROMFONT = 1

# The name of the bitmap font to be used, if enabled
BMFONT_NAME = ebdragon
